### ISSUE TITLE
Reference is made to the variable 'clock', but it does not exist. This should be timer.

### ISSUE THREAD

**Issue by libxx1** [raspberrypilearning/beat-the-goalie#21]
URL: /nl-NL/projects/beat-the-goalie/4

Er wordt verwezen naar de variabele 'klok', maar deze bestaat niet. Dit zou timer moeten zijn.

**Comment by libxx1** [comment]
Hey @majamanojlovic , would you be able to look at this please. Cheers, Liz

**Comment by majamanojlovic** [comment]
@libxx1 so weird - everything is correct in draft and master but the live version still shows "klok" instead of "timer". I'll re-publish it and see if anything changes.
